homebrew_apps_tools:
  - alfred
  - appcleaner
  - bitwarden
  - bitwarden-cli
  - charles # http proxy inspector for mobile apps
  - gfxcardstatus
  # - gpgtools-beta
  # - gmvault
  # - ipartition
  - hiddenbar
  # - keybase
  - keymapp
  # - kdiff3
  - meetingbar
  - monitorcontrol
  # - pock # touchbar macbook widget organizer
  - protonvpn
  - quitter
  - rectangle
  - the-unarchiver
  - utc-menu-clock
  - viscosity
  - xbar
