---

- file:
    src: "{{ roles_dir }}/tmux/files/.tmux.conf"
    dest: "{{ home }}.tmux.conf"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
  become: false

- file:
    src: "{{ roles_dir }}/tmux/files/.tmux.conf.local"
    dest: "{{ home }}.tmux.conf.local"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
  become: false
